/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppGitHubCalendar: typeof import('./components/AppGitHubCalendar.vue')['default']
    AppProject: typeof import('./components/AppProject.vue')['default']
    AppSkillsItems: typeof import('./components/AppSkillsItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSkills: typeof import('./components/TheSkills.vue')['default']
    TheTopBar: typeof import('./components/TheTopBar.vue')['default']
  }
}
